//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grifindo_Toys.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProfile
    {
        public int EmpId { get; set; }
        public string FullName { get; set; }
        public System.DateTime Dob { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UserRole { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public Nullable<decimal> OverTimeRate { get; set; }
        public Nullable<decimal> Allowances { get; set; }
    }
}
